#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not satisfy the requirements, you may need to use bash, ksh, or zsh.
#
#   (2) Put the JDK directory in the environment variable JAVA_HOME.
#
##############################################################################

# Force UTF-8 to handle non-ASCII characters properly in filenames
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

DIRNAME=$(cd "$(dirname "$0")" && pwd)
APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn() {
    echo "$*" >&2
}

die() {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
CYGWIN*)
    cygwin=true
    ;;
Darwin*)
    darwin=true
    ;;
MSYS* | MINGW*)
    msys=true
    ;;
NONSTOP*)
    nonstop=true
    ;;
esac

# Attempt to set APP_HOME
APP_HOME=$DIRNAME
[ -n "$APP_HOME" ] ||
    APP_HOME=$(
        cd "$DIRNAME/.." >/dev/null 2>&1
        pwd
    )

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell commands we need for proper escaping.
#   * For the avoidance of doubt, use double quotes "" to make variables
#     expand in strings, whereas single quotes '' prevent that.

set -- \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"

# Stop when "xargs" by default outputs the whole line if the length > 4096.
# Worse, the default SED regex used by xargs to detect this is "/.{4096}/"
# which will match strings that are exactly 4096 chars long, to avoid this
# we add a "$" to the pattern: "/.{4096}$/"
# This will only truncate strings longer than 4096 chars.
tr_SZ=$(printf '\1')
# shellcheck disable=SC2086
exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    -Dorg.gradle.wrapper.properties="$DIRNAME/gradle/wrapper/gradle-wrapper.properties" \
    -cp "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
