#!/bin/sh

# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME
APP_HOME="$( cd "$(dirname "$0")" && pwd )"

# Find JAVA_HOME
if [ -z "$JAVA_HOME" ]; then
    JAVA_EXE=$(command -v java)
    if [ -z "$JAVA_EXE" ]; then
        echo "Error: JAVA_HOME is not set and no 'java' command found in PATH." >&2
        exit 1
    fi
else
    JAVA_EXE="$JAVA_HOME/bin/java"
fi

if [ ! -x "$JAVA_EXE" ]; then
    echo "Error: Java executable not found at: $JAVA_EXE" >&2
    exit 1
fi

# Build the classpath
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

# Execute Gradle
exec "$JAVA_EXE" \
    -Xmx64m \
    -Xms64m \
    -Dorg.gradle.appname=$(basename "$0") \
    -Dorg.gradle.wrapper.properties="$APP_HOME/gradle/wrapper/gradle-wrapper.properties" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
