import json, os
OUT = os.path.join(os.path.dirname(__file__), '..', 'app', 'src', 'main', 'assets', 'lessons')
def S(heading=None, body=None, bullets=None, code=None):
    d = {}
    if heading: d['heading'] = heading
    if body: d['body'] = body
    if bullets: d['bullets'] = bullets
    if code: d['code'] = code.strip('\n')
    return d
def SUB(title, summary, *sections): return {'title': title, 'summary': summary, 'sections': list(sections)}
def REF(label, url): return {'label': label, 'url': url}
def write(tid, summary, sections, subtopics, takeaways, refs):
    json.dump({'summary': summary, 'sections': sections, 'subtopics': subtopics, 'takeaways': takeaways, 'references': refs},
              open(os.path.join(OUT, tid + '.json'), 'w'), indent=2, ensure_ascii=False)
C11 = REF('ISO/IEC 9899:2011 (C11) draft N1570', 'https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf')
GFG = lambda label, url: REF('Reference: ' + label, url)

write('pointers',
 "A pointer is a variable that holds the memory address of another object. Pointers let C share data without copying it, build linked structures, return multiple results from functions, and reach hardware registers.",
 [S('What a pointer is', "Every object lives at an address. The address-of operator `&x` produces it and the dereference operator `*p` reads or writes the object a pointer refers to. The pointer's type tells the compiler how many bytes `*p` touches and how to interpret them.",
    code="int x = 42;\nint *p = &x;     // p holds the address of x\n*p = 7;          // x is now 7\nprintf(\"%p %d\\n\", (void *)p, *p);"),
  S('Declaring and initializing', "Declare with `type *name;`. The `*` means 'pointer to' in a declaration and 'follow the pointer' in an expression. Initialize at declaration, either to a real address or to NULL.",
    bullets=["`int *p = &x;` points p at x.", "`int *p = NULL;` explicitly points at nothing.", "Print addresses with `%p` and cast to `void *`; print the pointed-to value with the type's own specifier."]),
  S('Size of a pointer', "All data pointers on a given platform have the same size because they only store an address: 4 bytes on 32-bit systems and 8 bytes on 64-bit systems. `sizeof(p)` is the pointer's size; `sizeof(*p)` is the size of the object it points to.",
    code="printf(\"%zu %zu %zu\\n\", sizeof(char *), sizeof(int *), sizeof(double *));  // 8 8 8 on x86-64"),
  S('Why pointers matter', None, bullets=["Pass-by-reference: a function modifies the caller's variable through its address.", "Dynamic memory: `malloc` returns a pointer to heap storage.", "Data structures: linked lists, trees, and graphs are nodes joined by pointers.", "Efficiency: pass a pointer to a large struct instead of copying it."]),
  S('Where pointers go wrong', None, bullets=["Dereferencing NULL or a wild pointer is undefined behavior (usually a segmentation fault).", "Using memory after `free` (dangling pointer).", "Reading or writing past the end of an array.", "Losing the only pointer to heap memory (leak)."])],
 [SUB('Types of special pointers', 'NULL, void, wild, and dangling pointers.',
      S(None, None, bullets=["NULL pointer: points to nothing; check it before use.", "void pointer: generic address holder; cast before dereferencing and no arithmetic.", "Wild pointer: declared but never initialized, so it holds garbage.", "Dangling pointer: refers to memory that was freed or left scope."])),
  SUB('Pointer to pointer', 'Why `int **pp` exists.',
      S(None, "A pointer is itself a variable and has an address, so you can point at it. A `**` parameter lets a function change which object the caller's pointer refers to, for example when allocating on the caller's behalf.",
        code="void alloc(int **out) { *out = malloc(sizeof **out); }\nint *p; alloc(&p);   // p now points to heap memory")),
  SUB('const and pointers', 'Pointer-to-const versus const pointer.',
      S(None, "Read the declaration right to left.", bullets=["`const int *p`: the int cannot be modified through p; p can be re-pointed.", "`int *const p`: p cannot be re-pointed; the int can be modified.", "`const int *const p`: neither can change."])),
  SUB('Arrays and pointers', 'An array name decays to a pointer to its first element.',
      S(None, "`a[i]` is defined as `*(a + i)`. In most expressions the array name becomes `&a[0]`, but `sizeof(a)` still gives the whole array's size, which is the main difference from a pointer.",
        code="int a[3] = {10, 20, 30};\nint *p = a;\nprintf(\"%d %d\\n\", p[1], *(a + 2));   // 20 30"))],
 ["`&` takes an address; `*` follows one.", "A pointer's own size is fixed per platform; the pointee's type sets how memory is read.", "Always initialize pointers and check for NULL before dereferencing.", "Most C memory bugs are pointer bugs: wild, dangling, out of bounds, or leaked."],
 [C11, GFG('Pointers in C (GeeksforGeeks)', 'https://www.geeksforgeeks.org/c/c-pointers/')])

write('memory-layout',
 "A running C program's memory is split into segments: text, initialized data, BSS, heap, and stack. Knowing which variable lands where explains lifetimes, crashes, and security bugs.",
 [S('The big picture', "From low to high addresses: text, initialized data, BSS, heap (grows up), a large gap, then the stack (grows down). When the two growing regions collide, memory is exhausted. Exact placement is randomized on modern systems (ASLR) but the ordering idea holds.",
    code="low addresses\n+---------------------+\n| text (code)         |  read-only, executable\n| initialized data    |  globals/statics with values\n| BSS                 |  zero-initialized globals/statics\n| heap  ->            |  malloc / calloc / realloc\n|        ...          |\n|            <-  stack|  locals, args, return addresses\n+---------------------+\nhigh addresses"),
  S('Text segment', None, bullets=["Holds the compiled machine instructions.", "Marked read-only so a stray write faults instead of corrupting code.", "Shared between processes running the same program."]),
  S('Initialized data segment', None, bullets=["Global and static variables that have a non-zero initial value.", "Stored in the executable file and loaded at start-up.", "Lives for the whole program run."], code="int g = 10;            // initialized data\nstatic int s = 20;     // initialized data"),
  S('BSS segment', "BSS holds global and static variables with no initializer (or initialized to zero). The loader zero-fills it, so the executable only records its size, not its contents, which keeps binaries small.", code="int counter;           // BSS\nstatic char buf[4096]; // BSS"),
  S('Heap', None, bullets=["Dynamic storage obtained with `malloc`, `calloc`, `realloc` and released with `free`.", "Grows toward higher addresses.", "Lifetime is controlled by the programmer, not by scope."]),
  S('Stack', None, bullets=["Each function call pushes a stack frame: arguments, return address, saved registers, and locals.", "Frames are popped automatically on return.", "Grows toward lower addresses on common architectures.", "Deep recursion or huge local arrays cause stack overflow."])],
 [SUB('Seeing the layout yourself', 'Use `size` and print addresses.',
      S(None, "The `size` tool reports text, data, and bss sizes of an executable. Adding an initialized global grows `data`; adding an uninitialized one grows `bss` only. Printing the address of a function, a global, a malloc result, and a local shows the ordering.",
        code="int g_init = 1; int g_bss;\nint main(void) {\n  int local; void *h = malloc(8);\n  printf(\"text %p data %p bss %p heap %p stack %p\\n\",\n         (void *)main, (void *)&g_init, (void *)&g_bss, h, (void *)&local);\n}")),
  SUB('Where do string literals and constants go?', 'Read-only data.',
      S(None, "String literals typically live in a read-only data section, so writing through `char *s = \"hi\"; s[0] = 'H';` is undefined behavior. Use `char s[] = \"hi\";` to get a modifiable copy on the stack.")),
  SUB('Virtual memory view', 'Why addresses look the same in every process.',
      S(None, "Each process sees its own virtual address space; the OS and MMU map pages to physical frames. Segments are just regions of that virtual space with different permissions (r-x for text, rw- for data, heap, stack).")),
  SUB('ELF sections vs runtime segments', 'Linker view and loader view.',
      S(None, "On Linux the object file groups bytes into sections (.text, .data, .bss, .rodata). The loader maps them into segments with permissions. `readelf -S` shows sections and `readelf -l` shows segments."))],
 ["Text is code (read-only); data/BSS hold globals; heap is manual; stack is automatic.", "BSS costs no file space; it is zeroed at load.", "Stack grows down, heap grows up on common platforms.", "String literals are read-only: do not modify them."],
 [C11, GFG('Memory layout of C programs (GeeksforGeeks)', 'https://www.geeksforgeeks.org/c/memory-layout-of-c-program/'), REF('Linux man-pages: elf(5)', 'https://man7.org/linux/man-pages/man5/elf.5.html')])

write('stack-vs-heap',
 "Stack memory is automatic, fast, and tied to function scope. Heap memory is manual, larger, and lives until you free it. Choosing correctly decides performance and bug surface.",
 [S('Stack allocation', None, bullets=["Locals and parameters are placed in a frame created on call and destroyed on return.", "Allocation is just moving the stack pointer, so it is very fast.", "Size is limited (often 8 MB on Linux by default).", "Data cannot outlive the function that created it."], code="void f(void) {\n  int x = 5;        // stack\n  char buf[64];     // stack\n}                   // both gone here"),
  S('Heap allocation', None, bullets=["`malloc`/`calloc`/`realloc` request memory from the allocator; `free` returns it.", "Lifetime is whatever you decide, independent of scope.", "Much larger than the stack, but allocation has bookkeeping cost.", "You must free exactly once and never use it afterward."], code="int *p = malloc(100 * sizeof *p);   // heap\nif (!p) return -1;\n/* use p */\nfree(p);\np = NULL;"),
  S('Comparison', None, bullets=["Management: automatic (stack) vs explicit (heap).", "Speed: stack is faster; heap pays allocator overhead.", "Size: stack small, heap large.", "Lifetime: scope-bound vs programmer-controlled.", "Typical failure: stack overflow vs leaks, dangling pointers, fragmentation."]),
  S('Pointers connect them', "A very common pattern is a pointer variable on the stack that refers to a block on the heap. When the function returns the pointer vanishes; if you did not free the block (or hand the pointer on), it leaks.")],
 [SUB('Stack overflow', 'Runaway recursion and huge locals.',
      S(None, "Each recursive call adds a frame. Missing base cases, or locals like `char big[10*1024*1024]`, exhaust the stack and the process is killed by SIGSEGV. Fix by bounding recursion, iterating, or moving large buffers to the heap.")),
  SUB('Heap fragmentation', 'Free memory that is unusable.',
      S(None, "Repeated allocate/free of different sizes leaves small holes. Total free memory may be large yet no single hole fits a request. Allocators mitigate with size classes and coalescing.")),
  SUB('Returning pointers to locals', 'A classic bug.',
      S(None, "Returning `&local` hands back stack memory that is already invalid. Return a heap pointer, a `static`, or fill a caller-provided buffer.", code="int *bad(void)  { int x = 1; return &x; }          // dangling\nint *good(void) { int *p = malloc(sizeof *p); *p = 1; return p; }")),
  SUB('Heap data structure vs heap memory', 'Same word, different things.',
      S(None, "The 'heap' in priority queues is a tree-shaped data structure. The 'heap' here is the process memory region used for dynamic allocation. They are unrelated."))],
 ["Stack: automatic, fast, scoped, small. Heap: manual, flexible, large, slower.", "Never return the address of a local variable.", "Every malloc needs exactly one free.", "Use the stack by default; use the heap when size or lifetime demands it."],
 [C11, GFG('Stack vs Heap memory allocation (GeeksforGeeks)', 'https://www.geeksforgeeks.org/stack-vs-heap-memory-allocation/')])

write('pointer-arithmetic',
 "Pointer arithmetic moves a pointer by whole elements, not bytes. The compiler multiplies by the pointed-to type's size, which is what makes array traversal with pointers work.",
 [S('The scaling rule', "Adding `n` to a pointer advances it by `n * sizeof(*p)` bytes. For an `int *` at address 1000 with 4-byte ints, `p + 1` is 1004 and `p - 1` is 996.", code="new_address = old_address ± (n × sizeof(type))"),
  S('Valid operations', None, bullets=["Increment/decrement: `p++`, `p--`.", "Add or subtract an integer: `p + n`, `p - n`.", "Subtract two pointers of the same type into the same array: gives the element count (type `ptrdiff_t`).", "Compare pointers: `<`, `<=`, `>`, `>=`, `==`, `!=`.", "Compare to NULL."]),
  S('Invalid operations', None, bullets=["Adding two pointers has no meaning and does not compile.", "Multiplying or dividing pointers.", "Arithmetic on `void *` (unknown element size; GCC allows it as an extension, standard C does not).", "Arithmetic on function pointers."]),
  S('Walking an array', code="int a[] = {1, 2, 3, 4, 5};\nint *p = a;\nfor (int i = 0; i < 5; i++) {\n  printf(\"%d \", *p);\n  p++;               // moves 4 bytes each step\n}\n// 1 2 3 4 5"),
  S('Subtracting pointers', "The result is a count of elements, not bytes.", code="int a[10];\nint *p = &a[2], *q = &a[7];\nptrdiff_t n = q - p;   // 5")],
 [SUB('Array indexing is pointer arithmetic', '`a[i]` equals `*(a + i)`.',
      S(None, "Because addition is commutative, `i[a]` is even legal, though you should never write it. Indexing and pointer walking compile to the same machine code in most cases.")),
  SUB('Staying inside bounds', 'What the standard allows.',
      S(None, "Forming a pointer is only defined within an array object or one element past its end. Dereferencing the one-past-end pointer, or going further, is undefined behavior even if it appears to work.")),
  SUB('char* vs int* stepping', 'Why byte pointers are special.',
      S(None, "`unsigned char *` moves one byte at a time, so it is used to inspect raw object representation. Casting `int *` to `char *` lets you view each byte of an int.", code="int x = 0x01020304;\nunsigned char *b = (unsigned char *)&x;\nfor (int i = 0; i < 4; i++) printf(\"%02x \", b[i]);")),
  SUB('Pointers and 2D arrays', 'Row stride is part of the type.',
      S(None, "For `int m[3][4]`, `m + 1` skips a whole row (16 bytes) because its type is `int (*)[4]`. This is why multidimensional array parameters need the inner dimensions."))],
 ["Arithmetic is scaled by the element size.", "Pointer minus pointer yields elements, not bytes.", "Stay within an array (or one past its end).", "Never add two pointers."],
 [C11, GFG('Pointer arithmetic in C (GeeksforGeeks)', 'https://www.geeksforgeeks.org/c/pointer-arithmetics-in-c-with-examples/')])

write('null-pointers',
 "A null pointer is a pointer that deliberately points at no object. It is the standard 'nothing here' value and the guard that separates safe code from crashes.",
 [S('Definition', "The C standard defines a null pointer constant as an integer constant expression with value 0, or such an expression cast to `void *`. The macro `NULL` (from `<stddef.h>`, `<stdio.h>`, `<stdlib.h>`) expands to it. Comparing any pointer to NULL tells you whether it refers to an object.", code="int *p = NULL;\nif (p == NULL) { /* nothing to use */ }"),
  S('Where NULL is used', None, bullets=["Initializing pointers before they have a target.", "Signalling failure: `malloc`, `fopen`, and `strstr` return NULL on failure or no match.", "Marking the end of linked lists, trees, and argument vectors (`argv[argc]` is NULL).", "Optional parameters: pass NULL to mean 'not provided'."]),
  S('Checking allocation results', code="int *p = malloc(5 * sizeof *p);\nif (p == NULL) {\n  fprintf(stderr, \"out of memory\\n\");\n  return 1;\n}"),
  S('What happens on dereference', "Dereferencing NULL is undefined behavior. On common desktop systems page zero is unmapped, so you get a segmentation fault, but the standard does not promise that, and optimizers may assume it never happens."),
  S('NULL vs void* vs uninitialized', None, bullets=["NULL is a value meaning 'no object'; it can be assigned to any pointer type.", "`void *` is a type: a generic pointer that can hold any object address.", "An uninitialized pointer holds garbage (a wild pointer) and is dangerous because you cannot test it."])],
 [SUB('Set pointers to NULL after free', 'A cheap defence against double-free and use-after-free.',
      S(None, "`free(NULL)` is defined to do nothing, so nulling a pointer after freeing makes an accidental second free harmless and makes later NULL checks meaningful.", code="free(p);\np = NULL;")),
  SUB('Null is not necessarily all-zero bits', 'A portability footnote.',
      S(None, "The source-level constant 0 converts to a null pointer, but the machine representation of a null pointer may not be all zero bits on exotic platforms. Always compare with NULL, never `memcmp` against zeros.")),
  SUB('Defensive APIs', 'Validate at the boundary.',
      S(None, "Public functions should check pointer parameters and return an error code; internal helpers may document 'must not be NULL' and use `assert`. Static analyzers can then flag callers that pass NULL.", code="int copy(char *dst, const char *src) {\n  if (!dst || !src) return -1;\n  /* ... */\n}")),
  SUB('nullptr in C23 and C++', 'A typed null.',
      S(None, "C++11 added `nullptr` and C23 adopted it, giving null a dedicated type so it cannot be confused with the integer 0 in overload or variadic contexts."))],
 ["NULL means 'points at nothing'; always check before dereferencing.", "Functions signal failure by returning NULL; test the result.", "Dereferencing NULL is undefined behavior.", "NULL is a value; void* is a type; uninitialized pointers are neither."],
 [C11, GFG('NULL pointer in C (GeeksforGeeks)', 'https://www.geeksforgeeks.org/c/null-pointer-in-c/')])

write('function-pointers',
 "A function pointer stores the address of code instead of data. It lets you choose which function runs at run time, enabling callbacks, jump tables, and plug-in style designs in plain C.",
 [S('Declaration and call', "Parentheses around `*name` are mandatory; without them you declare a function returning a pointer. The pointer's return and parameter types must match the target function.", code="int add(int a, int b) { return a + b; }\n\nint (*fp)(int, int);   // pointer to function(int,int) -> int\nfp = add;              // or &add\nprintf(\"%d\\n\", fp(10, 5));   // 15"),
  S('Properties', None, bullets=["Points to code, not data.", "Signature must match exactly.", "No arithmetic (no `fp++`).", "Can be stored in variables, arrays, structs, and passed or returned."]),
  S('Callbacks', "Passing a function pointer lets a generic routine call back into your code. The standard `qsort` and `bsearch` work this way.", code="void apply(int a, int b, int (*op)(int, int)) {\n  printf(\"%d\\n\", op(a, b));\n}\napply(10, 5, add);\napply(10, 5, sub);"),
  S('Arrays of function pointers', "A table of functions gives a fast dispatch without a long if/else chain.", code="int (*ops[])(int, int) = { add, sub, mul, div_ };\nint r = ops[1](10, 5);   // calls sub"),
  S('Structs with function pointers', "Putting function pointers in a struct emulates methods and is how the Linux kernel builds interfaces such as `file_operations`.", code="struct shape {\n  double (*area)(const struct shape *);\n  void   (*draw)(const struct shape *);\n};")],
 [SUB('Cleaner syntax with typedef', 'Make signatures readable.',
      S(None, "Function-pointer syntax is hard to read. Give the type a name once and reuse it.", code="typedef int (*binop_t)(int, int);\nbinop_t table[] = { add, sub };\nbinop_t pick(char c);")),
  SUB('qsort comparator walkthrough', 'The most common real-world callback.',
      S(None, "`qsort` sorts any array by calling your comparator with pointers to two elements. Return negative, zero, or positive. Avoid `a - b` for ints because it can overflow.", code="int cmp(const void *a, const void *b) {\n  int x = *(const int *)a, y = *(const int *)b;\n  return (x > y) - (x < y);\n}\nqsort(arr, n, sizeof arr[0], cmp);")),
  SUB('State machines and jump tables', 'Dispatch on an index.',
      S(None, "Interrupt vectors, VM opcodes, and protocol handlers are often arrays of function pointers indexed by an event or opcode, replacing a switch with a single indirect call.")),
  SUB('Security note', 'Overwritten function pointers are an attack target.',
      S(None, "If a buffer overflow overwrites a function pointer, the attacker controls where the next indirect call goes. Mitigations include bounds checking, read-only relocations, and control-flow integrity."))],
 ["Syntax: `ret (*name)(params)`; parentheses matter.", "Use for callbacks, dispatch tables, and struct-based interfaces.", "typedef the pointer type for readability.", "Check function pointers for NULL before calling."],
 [C11, GFG('Function pointer in C (GeeksforGeeks)', 'https://www.geeksforgeeks.org/c/function-pointer-in-c/')])

write('buffer-overflow',
 "A buffer overflow happens when a program writes more data into a fixed-size buffer than it can hold, spilling into adjacent memory. On the stack this can overwrite saved registers and the return address, handing control to an attacker.",
 [S('What goes wrong', "C does no bounds checking. Writing past the end of an array silently corrupts whatever sits next to it: other locals, a saved frame pointer, or the return address.", code="void vuln(const char *s) {\n  char buf[8];\n  strcpy(buf, s);   // no length check\n}"),
  S('Stack-based vs heap-based', None, bullets=["Stack-based: overflow a local buffer to reach the return address or function pointers. Most common and best understood.", "Heap-based: overflow a heap block to corrupt allocator metadata or neighbouring objects. Harder, but real."]),
  S('How stack smashing works', None, bullets=["A call pushes the return address; the callee allocates locals below it.", "Input longer than the buffer climbs upward over saved registers.", "The attacker chooses bytes that overwrite the return address.", "On `ret`, the CPU jumps to the attacker's chosen address."]),
  S('Dangerous functions', None, bullets=["`gets` (removed from C11), `strcpy`, `strcat`, `sprintf`, `scanf(\"%s\")` do no length checking.", "Safer: `fgets`, `snprintf`, `strncpy`/`strlcpy` (mind termination), `memcpy` with a verified length."]),
  S('Defences', None, bullets=["Stack canaries: a secret value before the return address, checked on return (`-fstack-protector`).", "NX / DEP: stack and heap pages are not executable.", "ASLR: randomize addresses so exploits cannot hard-code targets.", "Bounds-safe code, fortify (`-D_FORTIFY_SOURCE=2`), and sanitizers (`-fsanitize=address`)."])],
 [SUB('Worked example: 5-byte buffer', 'Why 9 bytes can crash and 8 may not.',
      S(None, "Compilers pad stack buffers to the machine word. A `char buf[5]` may occupy 8 bytes, so 8 input bytes can seem fine while 9 clobber adjacent data and fault. The absence of a crash is not proof of safety; it is undefined behavior either way.")),
  SUB('Return-oriented programming', 'Beating NX.',
      S(None, "When the stack is non-executable, attackers chain short existing code snippets ('gadgets') ending in `ret`, built by controlling the stack. ASLR and CFI make this harder.")),
  SUB('Off-by-one and format-string bugs', 'Related memory-safety classes.',
      S(None, "Writing `buf[n]` for a size-`n` array, or `printf(user_input)`, can be as exploitable as a large overflow. Always pass a constant format string.", code="printf(\"%s\", user);   // good\nprintf(user);          // bad")),
  SUB('Detecting overflows', 'Tools you should use.',
      S(None, "AddressSanitizer reports stack and heap overflows at run time with a precise location. Valgrind finds heap overruns. Static analyzers and compiler warnings (`-Wall -Wextra -Warray-bounds`) catch many at build time."))],
 ["C will not stop you writing past a buffer; you must bound every copy.", "Stack overflows can overwrite the return address and redirect execution.", "Prefer length-aware APIs and verify sizes.", "Layer defences: canaries, NX, ASLR, sanitizers."],
 [C11, GFG('Buffer overflow attack with example (GeeksforGeeks)', 'https://www.geeksforgeeks.org/c/buffer-overflow-attack-with-example/'), REF('CWE-121: Stack-based Buffer Overflow', 'https://cwe.mitre.org/data/definitions/121.html')])

write('use-after-free',
 "A use-after-free bug reads or writes memory through a pointer after that memory has been released. The pointer is dangling: it still holds the old address, but the storage may now belong to something else.",
 [S('How a pointer dangles', None, bullets=["Heap block freed while another pointer still references it.", "A function returns the address of a local variable.", "A pointer outlives the block-scoped variable it points to."]),
  S('Heap example', code="int *p = malloc(sizeof *p);\n*p = 10;\nfree(p);        // p is now dangling\n*p = 20;        // use-after-free: undefined behavior\n\nfree(p);\np = NULL;       // defensive: later checks and double free are safe"),
  S('Stack examples', code="int *f(void) {\n  int x = 5;\n  return &x;        // x dies at return\n}\n\nint *p;\n{ int a = 10; p = &a; }   // a out of scope\nprintf(\"%d\", *p);         // undefined"),
  S('Why it is dangerous', "The allocator may hand the freed block to a new allocation, so the stale pointer now aliases unrelated data. Attackers exploit this by getting a controlled object placed in the freed slot, turning a dangling write into corruption or code execution."),
  S('How to avoid it', None, bullets=["Set pointers to NULL immediately after `free`.", "Never return the address of a local; use `static`, heap memory, or an out-parameter.", "Give each allocation a single clear owner responsible for freeing.", "Test with AddressSanitizer, which poisons freed memory and reports the access."])],
 [SUB('Double free', 'Freeing the same block twice.',
      S(None, "A second `free` on the same pointer corrupts allocator bookkeeping and is exploitable. Nulling after free turns it into the harmless `free(NULL)`.")),
  SUB('Wild, dangling, null, void recap', 'Four pointer states to tell apart.',
      S(None, bullets=["Wild: never initialized.", "Dangling: initialized, then target released.", "NULL: intentionally empty.", "void*: generic type, not a state."])),
  SUB('Ownership patterns', 'Prevent aliasing bugs by design.',
      S(None, "Document who owns each pointer. Prefer APIs where the callee takes ownership or the caller keeps it, never both. Reference counting or arenas (free everything at once) reduce per-object lifetime errors.")),
  SUB('Detecting with ASan and Valgrind', 'See the bug, not just the crash.',
      S(None, "Compile with `-fsanitize=address -g` and run; the report shows the free site, the bad access, and the allocation site. Valgrind's memcheck gives similar traces without recompiling.", code="gcc -g -fsanitize=address uaf.c && ./a.out"))],
 ["A dangling pointer outlives its target; using it is undefined behavior.", "Null pointers after free; never return addresses of locals.", "Freed memory can be reused, so bugs can be silent and exploitable.", "Use sanitizers to catch these early."],
 [C11, GFG('Dangling, void, null and wild pointers (GeeksforGeeks)', 'https://www.geeksforgeeks.org/c/dangling-void-null-wild-pointers/'), REF('CWE-416: Use After Free', 'https://cwe.mitre.org/data/definitions/416.html')])

write('memory-leaks',
 "A memory leak is heap memory that is no longer reachable by the program but was never freed. It cannot be reused, so long-running programs slowly consume all available memory.",
 [S('What a leak is', "You allocate with `malloc`, lose every pointer to the block (or forget `free`), and the allocator still considers it in use. The block stays reserved until the process exits.", code="int *p = malloc(5 * sizeof *p);\np[0] = 10;\nreturn 0;   // missing free(p)"),
  S('Common causes', None, bullets=["Forgetting `free` on some path, especially early returns and error paths.", "Overwriting the only pointer: `p = malloc(...)` twice without freeing the first.", "Losing the pointer when it goes out of scope.", "Freeing a container but not the elements it owns."]),
  S('Consequences', None, bullets=["Gradual growth in memory use.", "Slowdown from paging and cache pressure.", "Out-of-memory failures; the OOM killer may terminate the process.", "Worst in servers and daemons that run for weeks."]),
  S('Prevention', None, bullets=["Pair every allocation with exactly one free in a clear owner.", "Use a single cleanup label (`goto cleanup`) so every error path frees resources.", "Do not overwrite a pointer before freeing it.", "Wrap resources in create/destroy function pairs."], code="int run(void) {\n  char *a = NULL, *b = NULL; int rc = -1;\n  a = malloc(100); if (!a) goto out;\n  b = malloc(200); if (!b) goto out;\n  /* work */ rc = 0;\nout:\n  free(b); free(a);\n  return rc;\n}"),
  S('Finding leaks', None, bullets=["Valgrind: `valgrind --leak-check=full ./prog` lists lost blocks with allocation stacks.", "AddressSanitizer's LeakSanitizer: `-fsanitize=address` reports leaks at exit.", "Static analysis (clang-tidy, cppcheck) flags obvious missing frees."])],
 [SUB('Leak categories', 'Definitely, indirectly, possibly lost.',
      S(None, "Valgrind distinguishes 'definitely lost' (no pointer remains), 'indirectly lost' (reachable only through a leaked block), 'possibly lost' (only interior pointers remain), and 'still reachable' (pointer exists at exit, often intentional globals).")),
  SUB('Leaks vs dangling pointers', 'Opposite mistakes.',
      S(None, "A leak is forgetting to free; a dangling pointer is using memory after freeing. Over-correcting one tends to cause the other, so ownership rules matter more than reflexes.")),
  SUB('Arena (region) allocation', 'Free in bulk.',
      S(None, "Allocate many short-lived objects from one arena and release the whole arena at once. It removes per-object lifetime tracking, eliminates most leaks, and is fast. Compilers and request handlers commonly use it.")),
  SUB('Resource leaks beyond memory', 'File descriptors and locks.',
      S(None, "The same discipline applies to `fopen`/`fclose`, sockets, and mutexes. Leaking descriptors hits the per-process limit long before RAM runs out."))],
 ["Leak = allocated, unreachable, never freed.", "Check every exit path, especially error returns.", "Use Valgrind or ASan/LSan in testing.", "Consider arenas or clear ownership to simplify cleanup."],
 [C11, GFG('Memory leak in C (GeeksforGeeks)', 'https://www.geeksforgeeks.org/what-is-memory-leak-how-can-we-avoid/'), REF('Valgrind manual: Memcheck', 'https://valgrind.org/docs/manual/mc-manual.html')])

write('struct-padding',
 "Compilers insert unused bytes inside and at the end of structs so every member sits at an address that suits the CPU. This padding makes struct sizes larger than the sum of their fields and depends on member order.",
 [S('Why alignment exists', "Processors fetch memory most efficiently when a value of size N sits at an address divisible by N. Misaligned access may need two memory operations, be slower, or fault on some architectures. So each type has a natural alignment.", bullets=["char: 1", "short: 2", "int / float: 4", "double / pointer (64-bit): 8"]),
  S('The padding rules', None, bullets=["Each member is placed at the next offset that is a multiple of its alignment.", "The struct's alignment is the largest member alignment.", "The total size is rounded up to a multiple of the struct's alignment (tail padding), so arrays of structs stay aligned."]),
  S('Worked examples (x86-64)', code="struct A { char c; short s; };            // 1 + pad1 + 2          = 4\nstruct B { short s; char c; int i; };      // 2 + 1 + pad1 + 4      = 8\nstruct C { char c; double d; int i; };     // 1 + pad7 + 8 + 4 + pad4 = 24\nstruct D { double d; int i; char c; };     // 8 + 4 + 1 + pad3      = 16"),
  S('Reducing padding', "Order members from largest alignment to smallest. Struct C and D hold the same fields, yet reordering shrinks 24 bytes to 16, which matters for large arrays and cache use.", bullets=["Group same-size fields together.", "Do not put small fields between large ones.", "Check with `sizeof` and `offsetof` rather than guessing."]),
  S('Packing', "Packing removes padding so the struct matches an external layout. It is used for network headers, file formats, and hardware registers.", code="#pragma pack(push, 1)\nstruct hdr { char c; short s; };   // size 3\n#pragma pack(pop)\n\nstruct hdr2 { char c; short s; } __attribute__((packed));")],
 [SUB('offsetof and alignof', 'Measure instead of assume.',
      S(None, "`offsetof(struct, member)` from `<stddef.h>` gives a member's byte offset; `_Alignof(type)` (C11) gives its alignment. Print both to see exactly where padding sits.", code="printf(\"%zu %zu\\n\", offsetof(struct C, d), _Alignof(double));")),
  SUB('Costs of packed structs', 'Why not pack everything.',
      S(None, "Taking the address of a packed member can yield a misaligned pointer, which is slower on x86 and can crash on stricter CPUs. Pack only when an external format demands it, and read fields with `memcpy`.")),
  SUB('Padding and security', 'Uninitialized padding bytes leak data.',
      S(None, "Padding bytes hold whatever was in memory. Copying a struct to a socket or file can leak stack contents, and comparing structs with `memcmp` can give false mismatches. Zero the struct first with `memset` or `= {0}`.")),
  SUB('Bit-fields', 'Packing flags inside an int.',
      S(None, "`unsigned a : 3;` stores a member in 3 bits. Layout, ordering, and straddling are implementation-defined, so bit-fields are unreliable for portable wire formats.", code="struct flags { unsigned ready : 1; unsigned mode : 3; };"))],
 ["Each member is aligned to its own size; the struct is padded to its largest alignment.", "Order members large to small to minimize padding.", "Use packing only for external layouts, and beware misaligned access.", "Zero structs before sending or hashing them."],
 [C11, GFG('Structure member alignment, padding and data packing (GeeksforGeeks)', 'https://www.geeksforgeeks.org/structure-member-alignment-padding-and-data-packing/')])

write('endianness',
 "Endianness is the order in which the bytes of a multi-byte value are stored in memory. Little-endian puts the least significant byte first; big-endian puts the most significant byte first. It matters whenever data crosses machines, files, or networks.",
 [S('The two orders', "For the 32-bit value 0x12345678 stored starting at address 0:", code="address:        00 01 02 03\nbig-endian:     12 34 56 78   (MSB at lowest address)\nlittle-endian:  78 56 34 12   (LSB at lowest address)"),
  S('Who uses which', None, bullets=["x86, x86-64, and most ARM systems run little-endian.", "Network protocols use big-endian, called network byte order.", "Some older architectures (SPARC, classic PowerPC, MIPS configurations) are big-endian; some CPUs are bi-endian.", "Single-byte values (char) are unaffected."]),
  S('Detecting host endianness', code="uint32_t x = 1;\nunsigned char *b = (unsigned char *)&x;\nputs(b[0] == 1 ? \"little-endian\" : \"big-endian\");"),
  S('Network byte order functions', "Convert between host and network order with these functions from `<arpa/inet.h>`. They are no-ops on big-endian hosts and byte swaps on little-endian ones.", bullets=["`htons` / `ntohs`: 16-bit host-to-network and back.", "`htonl` / `ntohl`: 32-bit.", "Use them for every multi-byte field you read from or write to a packet."], code="uint16_t port = htons(8080);\nuint32_t addr = ntohl(pkt->src_ip);"),
  S('Where it bites', None, bullets=["Reading binary files written on another architecture.", "Parsing protocol headers by casting a byte buffer to a struct.", "Hash or checksum code that assumes a byte order.", "Unicode UTF-16/32 text, which uses a Byte Order Mark (BOM) to declare order."])],
 [SUB('Bit order vs byte order', 'Not the same thing.',
      S(None, "Endianness describes byte order in memory. Bit numbering inside a byte is a separate convention (as in packet diagrams, where the most significant bit is drawn first). Protocol specs state both.")),
  SUB('Safe serialization', 'Never rely on struct layout for wire formats.',
      S(None, "Build packets by writing each field explicitly in a fixed order, or shift and mask: `buf[0] = v >> 8; buf[1] = v & 0xff;`. This is independent of host endianness, struct padding, and alignment.", code="static void put16(uint8_t *b, uint16_t v) { b[0] = v >> 8; b[1] = (uint8_t)v; }\nstatic uint16_t get16(const uint8_t *b) { return (b[0] << 8) | b[1]; }")),
  SUB('Byte swap builtins', 'Fast manual swaps.',
      S(None, "GCC and Clang provide `__builtin_bswap16/32/64`, and Linux has `le32toh`, `be32toh`, and friends in `<endian.h>` for explicit conversions to and from a named order.")),
  SUB('Why both orders exist', 'History and trade-offs.',
      S(None, "Big-endian reads naturally left to right and makes comparison of byte strings match numeric order. Little-endian lets a CPU read the low part of a value first and simplifies casting to a narrower type. Neither is faster in general; compatibility is the real cost."))],
 ["Endianness is byte order in memory: 0x12345678 is 12 34 56 78 (big) or 78 56 34 12 (little).", "Network byte order is big-endian; use htons/htonl and ntohs/ntohl.", "Serialize fields explicitly rather than casting buffers to structs.", "Single bytes are unaffected; only multi-byte values care."],
 [GFG('Little and big endian mystery (GeeksforGeeks)', 'https://www.geeksforgeeks.org/little-and-big-endian-mystery/'), REF('RFC 791 Appendix B: data transmission order', 'https://www.rfc-editor.org/rfc/rfc791'), REF('Linux man-pages: byteorder(3)', 'https://man7.org/linux/man-pages/man3/byteorder.3.html')])

write('undefined-behavior',
 "Undefined behavior (UB) means the C standard places no requirements on what happens. The program may crash, print garbage, appear to work, or be silently miscompiled, because the compiler is allowed to assume UB never occurs.",
 [S('Three kinds of unpredictable', None, bullets=["Undefined behavior: no requirements at all (null dereference, signed overflow).", "Unspecified behavior: the implementation picks among allowed options and need not document it (order of evaluating function arguments).", "Implementation-defined behavior: the compiler must document its choice (size of int, right shift of negative numbers)."]),
  S('Common sources', None, bullets=["Signed integer overflow: `INT_MAX + 1`.", "Division by zero.", "Out-of-bounds array access or pointer arithmetic.", "Dereferencing NULL or dangling pointers.", "Reading an uninitialized automatic variable.", "Modifying a string literal.", "Modifying a variable twice between sequence points: `i = i++ + ++i`.", "Strict-aliasing violations and misaligned access.", "Shifting by a negative or too-large amount."]),
  S('Examples', code="int a = INT_MAX; a + 1;          // signed overflow: UB\nint arr[4]; arr[5] = 0;          // out of bounds: UB\nint *p = NULL; *p = 1;           // null deref: UB\nchar *s = \"abc\"; s[0] = 'x';    // string literal write: UB\nint i = 4; int r = i++ * i++;    // unsequenced: UB"),
  S('Why the standard allows it', "Leaving behavior undefined lets compilers skip bounds and overflow checks and optimize aggressively. Signed overflow being UB lets `for (int i = 0; i < n; i++)` be assumed to terminate and be vectorized. The price is that bugs may not fail where they occur."),
  S('Consequences', None, bullets=["Results differ across compilers, versions, and optimization levels.", "Optimizers can delete checks that rely on UB, e.g. `if (x + 1 < x)` is removed for signed x.", "Security holes: many exploits start as UB.", "Debugging is hard because failures appear far from the cause."])],
 [SUB('Unsigned overflow is defined', 'Wraps modulo 2^N.',
      S(None, "Unsigned arithmetic is specified to wrap, so `UINT_MAX + 1 == 0` is fine. Signed overflow is not. Prefer unsigned types for bit manipulation and check ranges before signed arithmetic.", code="if (a > INT_MAX - b) { /* would overflow */ }\nelse sum = a + b;")),
  SUB('Sequence points', 'Order of side effects.',
      S(None, "Between two sequence points an object may be modified at most once, and its prior value may be read only to compute the new value. `a[i] = i++` and `printf(\"%d %d\", i++, i++)` violate this. Split such statements.")),
  SUB('Strict aliasing', 'Accessing an object through the wrong type.',
      S(None, "Reading a `float` through an `int *` is UB, letting compilers reorder or drop loads. To reinterpret bytes safely use `memcpy` or a `union` as documented by your compiler.", code="float f = 1.0f; uint32_t u;\nmemcpy(&u, &f, sizeof u);   // safe")),
  SUB('Finding UB', 'Sanitizers and warnings.',
      S(None, "Build with `-fsanitize=undefined,address -Wall -Wextra`. UBSan reports signed overflow, bad shifts, null deref, and misaligned access at run time. Static analyzers and `-O2` warnings catch more, and tools like Frama-C or CompCert's interpreter define behavior exactly.", code="gcc -g -O1 -fsanitize=undefined,address prog.c"))],
 ["UB gives the compiler license to assume it never happens.", "Signed overflow, out-of-bounds, null deref, uninitialized reads, and unsequenced modifications are UB.", "Unspecified and implementation-defined are different from undefined.", "Use -fsanitize=undefined and clean warnings to catch it."],
 [C11, GFG('Undefined behavior in C and C++ (GeeksforGeeks)', 'https://www.geeksforgeeks.org/undefined-behavior-c-cpp/'), REF('CERT C Coding Standard', 'https://wiki.sei.cmu.edu/confluence/display/c/SEI+CERT+C+Coding+Standard')])
print('ok')
